stages:
  generate_symptom_topics:
    cmd: python pipeline/symptom_topic_generator.py
    deps:
    - data/base/consolidated_products.csv
    - pipeline/symptom_topic_generator.py
    outs:
    - data/uc3/labels_generator/corex_topic_model.pkl
  generate_labels:
    cmd: python pipeline/labels_generator.py
    deps:
    - data/uc3/labels_generator/corex_topic_model.pkl
    - pipeline/labels_generator.py
    outs:
    - data/uc3/labels_generator/generated_labels.csv
  defects_classification:
    cmd: python pipeline/defects_classifier.py
    deps:
    - data/uc3/labels_generator/generated_labels.csv
    - pipeline/defects_classifier.py
    outs:
    - data/uc3/defects_classifier/svm_classifier.pkl
