stages:
  generate_symptom_topics:
    cmd: python pipeline/symptom_topic_generator.py
    deps:
    - data/base/consolidated_products.csv
    - pipeline/symptom_topic_generator.py
    outs:
    - data/uc3/labels_generator/biterm_topic_model.pkl
